baseURL = "https://underrum.dk/"
title = "Underrum"
defaultContentLanguage = "en-us"

theme = "underrum"

enableRobotsTXT = true

enableEmoji = true
footnoteReturnLinkContents = "↩"

[params]
  AuthorName = "Magnus Oksbøl Therkelsen"
  description = "Welcome to my personal blog about space, science, technology, maps, and much more!"
  mainSections = ["blog"]

[menu]
    [[menu.main]]
        name = "Blog"
        pre = ""
        post = ""
        url = "/blog/"
        weight = 1


    [[menu.main]]
        name = "About"
        pre = ""
        post = ""
        url = "/about/"
        weight = 2

[permalinks]
  blog = "/:year/:month/:title/"
